services:

    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www/html
            - ./.dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - /docker/
        ports:
            - "3333:80"
        links:
            - php

    php:
        build:
            context: ./.dockerfiles/php
        volumes:
            - .:/var/www/html
            - ./.dockerfiles/php/php.ini:/usr/local/etc/php/conf.d/docker-php.ini
            - /docker/
        links:
            - database

    database:
        image: mysql:8.3.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            TZ: UTC
        volumes:
            - ./var/docker/database:/var/lib/mysql
