services:

    php:
        build:
            dockerfile: remote.Dockerfile
        command: >
            sh -c "
                until mysqladmin ping -h database --silent; do
                    echo 'Waiting for the database...';
                    sleep 2;
                done;
                rm -rf var/cache && \
                composer install --no-dev --no-scripts -o -q && \
                bin/console cache:warmup --env=prod && \
                bin/console do:mi:mi -n && \
                bin/console remote:connect && \
                (bin/console remote:generate-random-locations ${GPS_START} &
                bin/console remote:sync-locations &
                wait)
            "
        environment:
            APP_ENV: "prod"
            DATABASE_URL: "mysql://root:password@database:3306/app?serverVersion=8.3.0&charset=utf8mb4"
        depends_on:
            - database
        links:
            - database
        networks:
            - local-network
            - trains-network

    database:
        image: mysql:8.3.0
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            TZ: UTC
        networks:
            - local-network

networks:
    local-network:
        internal: true
    trains-network:
        driver: bridge
