services:

    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www/html
            - ./.dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - /docker/
        ports:
            - "80:80"
        links:
            - php
        networks:
            - local-network
            - trains-network

    php:
        build:
            context: ./.dockerfiles/php
        volumes:
            - .:/var/www/html
        links:
            - database
        networks:
            - local-network

    database:
        image: mysql:8.3.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            TZ: UTC
        volumes:
            - ./var/docker/database:/var/lib/mysql
        networks:
            - local-network

    redis:
        image: redis:7.2
        ports:
            - "6379:6379"
        networks:
            - local-network

networks:
    local-network:
        driver: bridge
    trains-network:
        driver: bridge
